### ISSUE TITLE
Dashboard does not support source code with utf-8 characters

### ISSUE THREAD

**Issue by ScienJus** [iguazio/dashboard-controls#186]
When deploying a function that contains utf-8(eg. chinese) in the source code, The deployment will be successful but the source code did not change.

Because the dashboard uses `atob/btoa` that don't support utf-8 characters, so the source code in editor will fail to save.

The error logs:

```
DOMException: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
    at NclVersionCodeController.onChangeSourceCode (http://localhost:8070/assets/js/app-28d2d3af63.js:1795:108)
    at fn (eval at compile (http://localhost:8070/assets/js/vendor-e0775fc2ae.js:7:26044), <anonymous>:4:352)
    at NclMonacoController.r.(anonymous function) [as onChangeSourceCodeCallback] (http://localhost:8070/assets/js/vendor-e0775fc2ae.js:5:5329)
    at http://localhost:8070/assets/js/app-28d2d3af63.js:2674:218
    at h.$digest (http://localhost:8070/assets/js/vendor-e0775fc2ae.js:6:4906)
    at h.$apply (http://localhost:8070/assets/js/vendor-e0775fc2ae.js:6:6423)
    at http://localhost:8070/assets/js/vendor-e0775fc2ae.js:5:18537
```

I want to solve this problem with ~~`encodeURIComponent/decodeURIComponent`~~(or other third-party base64 libraries), like:

```
// save
lodash.set(ctrl.version, 'ui.versionCode', Base64.encode(sourceCode));

// load
ctrl.sourceCode = Base64.decode(savedSourceCode));
```

I'll work on this after we identify a solution.

**Comment by ScienJus** [comment]
My solution:

in iguazio.dashboard-controls:

1. add `js-base64` to bower.json
2. add `vendor/js-base64/base64.js` to vendor_files in build.config.js
3. register `window.Base64` as angular constant in iguazio.dashboard-controls.config.js
4. use `Base64.encode/decode` instead of `atob/btoa` in NclVersionCodeController

in nuclio:

1. add `js-base64` to bower.json
2. add `vendor/js-base64/base64.js` to vendor_files in build.config.js
3. register `window.Base64` as angular constant in third-party-components.service.js

If you can accept the introduction of a new third-party library, i'd like to create a pull request.

**Comment by eran-nussbaum** [comment]
Yes, from my investigation, too, I found out that a 3rd party is currently the best solution to support as many locales as possible (UTF-8).
I approve your suggestion, you can go ahead and create a pull request if you'd like.
Thanks
